# Generated by Django 2.0.5 on 2019-05-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0003_auto_20180625_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenes',
            name='tipo',
            field=models.CharField(choices=[('hematologia', 'Hematologia'), ('orina', 'Orina'), ('Quimica Sanguinea', 'quimica sanguinea'), ('Hormonas', 'hormonas')], max_length=30),
        ),
    ]
